export const theme = {
  colors: {
    primary: "#FF007A",
    black: "#000000",
    darkGray: "#FF007A",
    backGround: "#FFFFFF",
    BrandGreen: "#46B455",
  },
  fonts: {
    body: "Arial, sans-serif",
    heading: "Helvetica, sans-serif",
  },
  breakpoints: {
    mobile: "576px",
    tablet: "768px",
    desktop: "992px",
    largeDesktop: "1200px",
  },
  sizes: {
    px: [
      "2px",
      "4px",
      "6px",
      "8px",
      "10px",
      "12px",
      "14px",
      "16px",
      "18px",
      "20px",
      "22px",
      "24px",
      "26px",
      "28px",
      "30px",
      "32px",
      "34px",
      "36px",
      "38px",
      "40px",
    ],
    rem: ["1rem", "2rem", "3rem"],
  },
};
