export const commonErrors = {
  InvalidInput: "Invalid input provided",
  ResourceNotFound: "Resource not found",
  DatabaseError: "Error accessing the database",
  DatabaseInsertError: "Error inserting value",
  DatabaseFindOneError: "Error finding requested item",
  DatabaseUpdateOneError: "Error update document",
  UnauthorizedAccess: "Unauthorized access",
  AuthenticationFailed: "Authentication failed",
  DuplicateEntry: "Duplicate entry",
  FileUploadError: "Error uploading file",
  NetworkError: "Network error",
  TimeoutError: "Request timeout",
  PermissionDenied: "Permission denied",
  ValidationError: "Validation error",
  HashError: "Error hashing password",
  UuidvError: "Error creating UuidvError",
  ShapeError: "Invalid Shape element",
  InvalidKeyTypes: "Invalid Keys Types",
  JwtError: "Error sign jwt token",
};
